version: '3.8'
services:
  server:
    build: ./server
    container_name: server
    ports:
      - "5000:5000"
    networks:
      - mern-network
    env_file:
      - ./server/.env

  client:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
